#!/bin/bash

if git diff --cached --name-only | grep -q '^src-tauri/'; then
    cargo clippy --manifest-path ./src-tauri/Cargo.toml
    if [ $? -ne 0 ]; then
        echo "Clippy found issues in src-tauri. Please fix them before pushing."
        exit 1
    fi
fi

remote_name="$1"
remote_url=$(git remote get-url "$remote_name")

case "$remote_url" in
    *github.com[:/]clash-verge-rev/clash-verge-rev*)
        echo "[pre-push] Detected push to clash-verge-rev/clash-verge-rev ($remote_url)"
        echo "[pre-push] Running pnpm format:check..."

        pnpm format:check
        if [ $? -ne 0 ]; then
            echo "❌ Code format check failed. Please fix formatting before pushing."
            exit 1
        fi
        ;;
    *)
        echo "[pre-push] Not pushing to target repo. Skipping format check."
        ;;
esac

exit 0
